IMPORT LIBRARIES

In [9]:
# This line of code will import the pandas library into the jupyter notebook. 
# Pandas is a python package that we will use to analyse and manipulate our dataset.
# Using the 'as' syntax, we were able to assign the alias 'pd' to panda to reference its functions easier throughout the script.

import pandas as pd

LOAD DATASET

In [10]:
# This line of code loads our dataset, which is a CSV file named 'twitter_training.csv,' into a DataFrame called 'df.' 
# According to W3Schools, a DataFrame is a 2D data structure which can be visualized with a table with rows and columns.
# The function pd.read_csv() reads our dataset and automatically determines the column headers and data types for the creation of the DataFrame df.

df = pd.read_csv('twitter_training.csv')

INITIAL UNDERSTANDING

In [11]:
# The function head() displays the first five rows of the df DataFrame. 
# This is a usual way for us to quickly inspect the column headers and their content.
# Through this, we are able to get a quick understanding of the structure of the data we are working with without loading all of it into memory.

df.head()

      label                                            premise
0  Positive  im getting on borderlands and i will murder yo...
1  Positive  I am coming to the borders and I will kill you...
2  Positive  im getting on borderlands and i will kill you ...
3  Positive  im coming on borderlands and i will murder you...
4  Positive  im getting on borderlands 2 and i will murder ...

In [12]:
# The shape() function is used to return a tuple showing the dimensionality of the DataFrame df (pandas, 2024).
# The first value 74 682 is the number of records in our dataset (rows), while the second value 2 is the number of columns.
df.shape

(74682, 2)

In [13]:
# The info() function from the pandas library prints more information about our df DataFrame (pandas, 2024). 
# It includes information like the numbers of rows (indexed from 0 to 61 691), the number of columns (2), the different column names ('label' and 'premise'), the number of non-null rows, the data type of each columm ('object'), and the total memory usage of the dataset in RAM.
# It is important to note that the number of non-null values in the premise column is larger than the total number of records. This means that there are some values in the premise column that are null and needs to be cleaned later.

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 74682 entries, 0 to 74681
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    74682 non-null  object
 1   premise  73996 non-null  object
dtypes: object(2)
memory usage: 1.1+ MB

In [14]:
# This line of code is used to list all column names in the DataFrame df.
# Throught this, we were able to confirm that expected columns like 'label' and 'premise' are present in the DataFrame.

df.columns

Index(['label', 'premise'], dtype='object')

In [15]:
# This prints all the unique values in the 'label' column, identifying all sentiment categories in the dataset. 
# For the purposes of this analysis, we have elected to delete all records with 'irrelevant' values because they do not contribute to our task.

print(df['label'].unique())

['Positive' 'Neutral' 'Negative' 'Irrelevant']

In [16]:
print(df['label'].value_counts())

label
Negative      22542
Positive      20832
Neutral       18318
Irrelevant    12990
Name: count, dtype: int64

In [17]:
df = df[df['label'].str.lower() != 'irrelevant']

In [18]:
print(df['label'].value_counts())

label
Negative    22542
Positive    20832
Neutral     18318
Name: count, dtype: int64

In [19]:
df.reset_index(drop=True, inplace=True)

In [20]:
df.shape

(61692, 2)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 61692 entries, 0 to 61691
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    61692 non-null  object
 1   premise  61121 non-null  object
dtypes: object(2)
memory usage: 964.1+ KB

In [22]:
df[df['premise'].isnull()]

          label premise
61      Neutral     NaN
493     Neutral     NaN
511     Neutral     NaN
661    Positive     NaN
985    Positive     NaN
...         ...     ...
60994  Positive     NaN
60995  Positive     NaN
61431  Positive     NaN
61432  Positive     NaN
61433  Positive     NaN

[571 rows x 2 columns]

In [23]:
df = df.dropna(subset=['premise'])

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 61121 entries, 0 to 61691
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   label    61121 non-null  object
 1   premise  61121 non-null  object
dtypes: object(2)
memory usage: 1.4+ MB

Source: Kaggle - Twitter Sentiment Analysis by Passionate-NLP

Description:
    
    - This dataset has two columns: label and premise.
    
    - Textual data (tweets) is in the premise column, while sentiment labels are in the label column.
    
    - Sentiment categories include: positive, negative, and neutral. 
    
    - Initially, there was an irrelevant category however, we elected to drop all records with this label so that our data will be more specific and have better polarity.
    
    - The final cleaned dataset contains 61 692 rows and 2 columns.

In [25]:
BIBLIOGRAPHY

NameError: name 'BIBLIOGRAPHY' is not defined